### get all topics
GET http://localhost:5001/api/goals

### get a topic
GET http://localhost:5001/api/goals/

### delete a topic
DELETE http://localhost:5001/api/goals/

### update a topic
PATCH http://localhost:5001/api/goals/
Content-Type: application/json

{
  "dislikes": 50
}

### post a topic
POST http://localhost:5001/api/goals
Content-Type: application/json

{
  "subject": "Monday Goal",
  "description": "finish a goal setting app",
  "deadline": "2022-11-22"
}